/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmisRenderer: typeof import('./components/amis/AmisRenderer.vue')['default']
    BaseLayout: typeof import('./components/layout/BaseLayout.vue')['default']
    ExceptionError: typeof import('./components/exception/ExceptionError.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    NavBar: typeof import('./components/navbar/NavBar.vue')['default']
    PageBreadcrumb: typeof import('./components/breadcrumb/PageBreadcrumb.vue')['default']
    PageLayout: typeof import('./components/layout/PageLayout.vue')['default']
    PageMenu: typeof import('./components/menu/PageMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/tabBar/TabBar.vue')['default']
    TabItem: typeof import('./components/tabBar/TabItem.vue')['default']
  }
}
